specVersion: 0.2.0
name: testnet-subql-barnacle-evm
version: 0.0.4
description: This SubQuery project can be use as a st...
repository: https://github.com/octopus-appchains/testnet-subql-barnacle-evm.git
schema:
  file: ./schema.graphql
network:
  endpoint: >-
    wss://gateway.testnet.octopus.network/barnacle-evm/wj1hhcverunusc35jifki19otd4od1n5
  genesisHash: "0xd0599a36a2fb1e958d74c51c439b63f5ee91b7c107940caec1ec78958c2d3422"
  dictionary: https://api.subquery.network/sq/subquery/moonbeam-dictionary
  chaintypes:
    file: ./dist/chaintypes.js
dataSources:
  - kind: substrate/Runtime
    startBlock: 1
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: handleBlock
          kind: substrate/BlockHandler
        - handler: handleEvent
          kind: substrate/EventHandler
        - handler: handleCall
          kind: substrate/CallHandler
        - handler: systemTokenTransferEvent
          kind: substrate/EventHandler
          filter:
            module: balances
            method: Transfer
  - kind: substrate/FrontierEvm
    startBlock: 1
    processor:
      file: "./node_modules/@subql/contract-processors/dist/frontierEvm.js"
      options:
        # Must be a key of assets
        abi: erc20
    assets:
      erc20:
        file: "./erc20.abi.json"
    mapping:
      file: "./dist/index.js"
      handlers:
        - handler: handleErc20Transaction
          kind: substrate/FrontierEvmEvent
          filter:
            topics:
              - Transfer(address indexed from,address indexed to,uint256 value)
        - handler: handleErc20Approval
          kind: substrate/FrontierEvmEvent
          filter:
            topics:
              - Approval(address indexed owner, address indexed spender, uint256 value)
  - kind: substrate/FrontierEvm
    startBlock: 1
    processor:
      file: "./node_modules/@subql/contract-processors/dist/frontierEvm.js"
      options:
        # Must be a key of assets
        abi: sopometa
    assets:
      erc20:
        file: "./sopometa.abi.json"
    mapping:
      file: "./dist/index.js"
      handlers:
        - handler: handleSopometaForsell
          kind: substrate/FrontierEvmEvent
          filter:
            topics:
              - Forsell(uint256 indexed sopo_id, uint256 indexed price)
        - handler: handleSopometaListandforsell
          kind: substrate/FrontierEvmEvent
          filter:
            topics:
              - Listandforsell(address indexed from, address to, uint256 sopo_id, uint256 nft_id, address indexed nft_programe_address, uint256 indexed price)
        - handler: handleSopometaListed
          kind: substrate/FrontierEvmEvent
          filter:
            topics:
              - Listed(address indexed from, address to, uint256 indexed sopo_id, uint256 nft_id, address indexed nft_programe_address)
        - handler: handleSopometaNewoffer
          kind: substrate/FrontierEvmEvent
          filter:
            topics:
              - Newoffer(address indexed from, address indexed to, uint256 sopo_id, uint256 indexed price)
        - handler: handleSopometaSelled
          kind: substrate/FrontierEvmEvent
          filter:
            topics:
              - Selled(address indexed from, address to, uint256 sopo_id, uint32 indexed selled_at, uint256 nft_id, address indexed nft_programe_address, address owner)
        - handler: handleSopometaWithdraw
          kind: substrate/FrontierEvmEvent
          filter:
            topics:
              - Withdraw(address indexed from, address to, uint256 sopo_id, uint256 nft_id, address indexed nft_programe_address, uint32 indexed withdrawout_at)
