specVersion: 1.0.0
name: testnet-subql-barnacle-evm
version: 1.0.0
runner:
  node:
    name: "@subql/node"
    version: ">=1.13.3"
  query:
    name: "@subql/query"
    version: ">=1.2.1"
description: This SubQuery project can be use as a st...
repository: https://github.com/octopus-appchains/testnet-subql-barnacle-evm.git
schema:
  file: ./schema.graphql
network:
  endpoint: >-
    wss://gateway.testnet.octopus.network/barnacle-evm/wj1hhcverunusc35jifki19otd4od1n5
  genesisHash: "0xaf4fcd6531f248060ddf6e9be4630522d85eaa33a3a130767cd30811b2f02fdd"
  chaintypes:
    file: ./dist/chaintypes.js
dataSources:
  - kind: substrate/Runtime
    startBlock: 1
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: handleBlock
          kind: substrate/BlockHandler
