specVersion: 0.2.0
name: testnet-subql-barnacle-evm
version: 0.0.4
description: This SubQuery project can be use as a st...
repository: https://github.com/octopus-appchains/testnet-subql-barnacle-evm.git
schema:
  file: ./schema.graphql
network:
  endpoint: >-
    wss://gateway.testnet.octopus.network/barnacle-evm/wj1hhcverunusc35jifki19otd4od1n5
  genesisHash: "0xbd46443c4c65faf52b5f61b480e6dc693adffd498bd91d93c05e9d797fd61216"
  dictionary: https://api.subquery.network/sq/subquery/moonbeam-dictionary
  chaintypes:
    file: ./dist/chaintypes.js
dataSources:
  - kind: substrate/Runtime
    startBlock: 1
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: handleBlock
          kind: substrate/BlockHandler
  - kind: substrate/FrontierEvm
    startBlock: 1
    processor:
      file: "./node_modules/@subql/contract-processors/dist/frontierEvm.js"
      options:
        # Must be a key of assets
        abi: sopometa721nft
    assets:
      sopometa721nft:
        file: "./sopometa721nft.abi.json"
    mapping:
      file: "./dist/index.js"
      handlers:
        - handler: handleSopometa721nftApproval
          kind: substrate/FrontierEvmEvent
          filter:
            topics:
              - Approval(address indexed owner, address indexed approved, uint256 indexed tokenId)
        - handler: handleSopometa721nftApprovalForAll
          kind: substrate/FrontierEvmEvent
          filter:
            topics:
              - ApprovalForAll(address indexed owner, address indexed operator, bool approved)
        - handler: handleSopometa721nftTransfer
          kind: substrate/FrontierEvmEvent
          filter:
            topics:
              - Transfer(address indexed from, address indexed to, uint256 indexed tokenId)
  - kind: substrate/FrontierEvm
    startBlock: 1
    processor:
      file: "./node_modules/@subql/contract-processors/dist/frontierEvm.js"
      options:
        # Must be a key of assets
        abi: sopometaMarket
    assets:
      sopometaMarket:
        file: "./sopometaMarket.abi.json"
    mapping:
      file: "./dist/index.js"
      handlers:
        - handler: handleSopometaMarketApprovalForAll
          kind: substrate/FrontierEvmEvent
          filter:
            topics:
              - ApprovalForAll(address indexed account, address indexed operator, bool approved)
        - handler: handleSopometaMarketTransferBatch
          kind: substrate/FrontierEvmEvent
          filter:
            topics:
              - TransferBatch(address indexed operator, address indexed from, address indexed to, uint256[] ids, uint256[] values)
        - handler: handleSopometaMarketTransferSingle
          kind: substrate/FrontierEvmEvent
          filter:
            topics:
              - TransferSingle(address indexed operator, address indexed from, address indexed to, uint256 id, uint256 value)
        - handler: handleSopometaMarketURI
          kind: substrate/FrontierEvmEvent
          filter:
            topics:
              - URI(string value, uint256 indexed id)
